# version: '3'

services:
  app:
    container_name: ocr-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
